"""Orchestrator: gather context -> branch -> develop -> PR. Status comments at each step."""
from __future__ import annotations

import logging
import os
import re
import sys
import traceback
from pathlib import Path

# allow skills/ import when run from repo root
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from skills.create_branch import create_branch  # noqa: E402
from skills.create_pr import create_pr  # noqa: E402
from skills.develop import develop  # noqa: E402
from skills.gather_context import gather_context  # noqa: E402
from skills.post_comment import post_comment  # noqa: E402

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)
logger = logging.getLogger("claude_automation")

TRIGGER = re.compile(r"@claude\s+fix\s+this", re.IGNORECASE)


def _env(name: str, required: bool = True) -> str:
    val = os.environ.get(name, "")
    if required and not val:
        raise RuntimeError(f"missing env var: {name}")
    return val


def _slugify(text: str, max_len: int = 40) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "-", text).strip("-").lower()
    return (s or "task")[:max_len]


def _safe_comment(repo: str, issue: int, token: str, body: str) -> None:
    try:
        post_comment(repo, issue, body, token=token)
    except Exception as e:  # noqa: BLE001
        logger.warning("status comment failed: %s", e)


def main() -> int:
    github_token = _env("GITHUB_TOKEN")
    anthropic_key = os.environ.get("CLAUDE_CODE_OAUTH_TOKEN") or os.environ.get(
        "ANTHROPIC_API_KEY", ""
    )
    if not anthropic_key:
        raise RuntimeError("missing CLAUDE_CODE_OAUTH_TOKEN or ANTHROPIC_API_KEY")

    repo = _env("REPO")  # owner/name
    issue_number = int(_env("ISSUE_NUMBER"))
    comment_body = _env("COMMENT_BODY", required=False) or ""
    issue_title = os.environ.get("ISSUE_TITLE", f"issue-{issue_number}")
    issue_body = os.environ.get("ISSUE_BODY", "")
    base_branch = os.environ.get("BASE_BRANCH", "main")

    if not TRIGGER.search(comment_body):
        logger.info("trigger phrase not found, exiting cleanly")
        return 0

    branch = f"claude/issue-{issue_number}-{_slugify(issue_title)}"
    task_text = f"Issue #{issue_number}: {issue_title}\n\n{issue_body}".strip()

    try:
        _safe_comment(
            repo,
            issue_number,
            github_token,
            f"Claude automation started. Branch: `{branch}`",
        )

        logger.info("step 1: gather context")
        context = gather_context(task_text, repo_root=str(ROOT))

        logger.info("step 2: create branch %s from %s", branch, base_branch)
        create_branch(branch, base_branch=base_branch, cwd=str(ROOT), push=True)
        _safe_comment(repo, issue_number, github_token, f"Branch `{branch}` created.")

        logger.info("step 3: develop changes")
        result = develop(
            description=task_text,
            file_context=context,
            repo_root=str(ROOT),
            api_key=anthropic_key,
            branch=branch,
            push=True,
        )
        if not result["committed"]:
            _safe_comment(
                repo,
                issue_number,
                github_token,
                "Claude produced no committable changes. Aborting.",
            )
            return 1

        _safe_comment(
            repo,
            issue_number,
            github_token,
            f"Committed: `{result['commit_message']}`\nFiles: "
            + ", ".join(f"`{c}`" for c in result["changes"]),
        )

        logger.info("step 4: create PR")
        pr_title = result["commit_message"]
        pr_body = (
            f"Closes #{issue_number}\n\n"
            f"Automated PR generated by Claude for issue #{issue_number}.\n\n"
            f"**Files changed:**\n"
            + "\n".join(f"- `{c}`" for c in result["changes"])
        )
        pr_url = create_pr(
            repo_full_name=repo,
            branch=branch,
            title=pr_title,
            body=pr_body,
            base_branch=base_branch,
            token=github_token,
            labels=["claude-automation"],
            issue_number=issue_number,
        )
        logger.info("PR ready: %s", pr_url)
        _safe_comment(repo, issue_number, github_token, f"PR ready: {pr_url}")
        return 0

    except Exception as e:  # noqa: BLE001
        tb = traceback.format_exc()
        logger.error("automation failed: %s\n%s", e, tb)
        _safe_comment(
            repo,
            issue_number,
            github_token,
            f"Claude automation failed: `{e}`\n\n<details><summary>traceback</summary>\n\n"
            f"```\n{tb[-1500:]}\n```\n</details>",
        )
        return 1


if __name__ == "__main__":
    sys.exit(main())
